name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  swift-build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: swift test

